# Generated by Django 2.0.5 on 2018-05-22 01:51

import DjangoUeditor.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='文档标题')),
                ('context', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='文档内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最近更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='项目名')),
                ('intr', models.TextField(verbose_name='项目介绍')),
                ('owner', models.CharField(max_length=128, verbose_name='项目负责人')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='项目创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Sum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('create_num', models.IntegerField()),
                ('update_num', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='belong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.Project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='article',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_user', to=settings.AUTH_USER_MODEL, verbose_name='文档创建人'),
        ),
        migrations.AddField(
            model_name='article',
            name='last_update_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_update_user', to=settings.AUTH_USER_MODEL, verbose_name='最近更新人'),
        ),
    ]
