# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-21 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='intr',
            field=models.TextField(),
        ),
    ]
